// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Providers',
      items: [{type: 'autogenerated', dirName: 'providers'}],
    },
    {
      type: 'category',
      label: 'Customers',
      items: [{type: 'autogenerated', dirName: 'customers'}],
    },
    {
      type: 'category',
      label: 'Developers',
      items: [{type: 'autogenerated', dirName: 'developers'}],
    },
    {
      type: 'category',
      label: 'Affiliate',
      items: [{type: 'autogenerated', dirName: 'affiliate-system'}],
    },
    'terms',
    'privacy',
    'license',
  ],
};

export default sidebars;
